apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: srunner-dep
  name: srunner-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: srunner-dep
    spec:
      containers:
      - image: gcr.io/$PROJECT_ID/sinmetal/srunner/master
        name: srunner-dep
        resources:
          limits:
            cpu: "2"
          requests:
            cpu: "1"
        envFrom:
          - configMapRef:
              name: srunner-config